[package]
name = "rust-displaytest"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-graphics = "0.8.1"
ssd1306 = "0.8.4"
rppal = "0.17.1"
embedded-hal = "0.2.7"  # This version is still the latest stable for 0.2.x
display-interface = "0.4.1"
display-interface-spi = "0.4.1"